gcc -Ofast -ffast-math -msse4.1 -o TestGame main.c \
Window1/Window1_t.h \
Window1/Window1_t.c \
Time1/Time1_t.h \
Time1/Time1_t.c \
Math1/WTMath.h \
Math1/WTMath.c \
Shaders1/Shaders1.h \
Shaders1/ShProgram1.h \
Shaders1/ShProgram1.c \
Buffs1/Buff1.h \
Buffs1/Buff1.c \
Skybox1/Skybox1.h \
Skybox1/Skybox1.c \
StaticObjects1/StaticObjects1.h \
StaticObjects1/StaticObjects1.c \
Transform1/Transform1.h \
Transform1/Transform1.c \
Lights1/Light1.h \
Lights1/Light1.c \
Water1/Water1.h \
Water1/Water1.c \
Shaders1/MainShader.h \
Shaders1/MainShader.c \
Camera1/Camera1.h \
Camera1/Camera1.c \
Particles1/Particles1.h \
Particles1/Particles1.c \
Picking1/Picking.h \
Picking1/Picking.c \
Heightmap1/Heightmap1.h \
Heightmap1/Heightmap1.c \
OLlist1/OLlist1.h \
OLlist1/OLlist1.c \
-DGLEW_STATIC -lGL -lGLEW -lGLX -lm -DSHM -lassimp -lglfw
